name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      env:
        CARGO_INCREMENTAL: 0
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
    - name: Archive codecov
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
      
